INSERT INTO municipalities (municipality) VALUES ("Αβδήρων Νομού Ξάνθης");
INSERT INTO municipalities (municipality) VALUES ("Αλεξανδρούπολης Νομού Έβρου");
INSERT INTO municipalities (municipality) VALUES ("Αρριανών Νομού Ροδόπης");
INSERT INTO municipalities (municipality) VALUES ("Διδυμοτείχου Νομού Έβρου");
INSERT INTO municipalities (municipality) VALUES ("Δοξάτου Νομού Δράμας");
INSERT INTO municipalities (municipality) VALUES ("Δράμας Νομού Δράμας");
INSERT INTO municipalities (municipality) VALUES ("Θάσου Νομού Καβάλας");
INSERT INTO municipalities (municipality) VALUES ("Ιάσμου Νομού Ροδόπης");
INSERT INTO municipalities (municipality) VALUES ("Καβάλας Νομού Καβάλας");
INSERT INTO municipalities (municipality) VALUES ("Κάτω Νευροκοπίου Νομού Δράμας");
INSERT INTO municipalities (municipality) VALUES ("Κομοτηνής Νομού Ροδόπης");
INSERT INTO municipalities (municipality) VALUES ("Μαρώνειας-Σαπών Νομού Ροδόπης");
INSERT INTO municipalities (municipality) VALUES ("Μύκης Νομού Ξάνθης");
INSERT INTO municipalities (municipality) VALUES ("Νέστου Νομού Καβάλας");
INSERT INTO municipalities (municipality) VALUES ("Ξάνθης Νομού Ξάνθης");
INSERT INTO municipalities (municipality) VALUES ("Ορεστιάδας Νομού Έβρου");
INSERT INTO municipalities (municipality) VALUES ("Παγγαίου Νομού Καβάλας");
INSERT INTO municipalities (municipality) VALUES ("Παρανεστίου Νομού Δράμας");
INSERT INTO municipalities (municipality) VALUES ("Προσοτσάνης Νομού Δράμας");
INSERT INTO municipalities (municipality) VALUES ("Σαμοθράκης Νομού Έβρου");
INSERT INTO municipalities (municipality) VALUES ("Σουφλίου Νομού Έβρου");
INSERT INTO municipalities (municipality) VALUES ("Τοπείρου Νομού Ξάνθης");
INSERT INTO municipalities (municipality) VALUES ("Αλεξάνδρειας Νομού Ημαθίας");
INSERT INTO municipalities (municipality) VALUES ("Αλμωπίας Νομού Πέλλας");
INSERT INTO municipalities (municipality) VALUES ("Αμπελοκήπων-Μενεμένης Νομού Θεσσαλονίκης");
INSERT INTO municipalities (municipality) VALUES ("Αμφίπολης Νομού Σερρών");
INSERT INTO municipalities (municipality) VALUES ("Αριστοτέλη Νομού Χαλκιδικής");
INSERT INTO municipalities (municipality) VALUES ("Βέροιας Νομού Ημαθίας");
INSERT INTO municipalities (municipality) VALUES ("Βισαλτίας Νομού Σερρών");
INSERT INTO municipalities (municipality) VALUES ("Βόλβης Νομού Θεσσαλονίκης");
INSERT INTO municipalities (municipality) VALUES ("Δέλτα Νομού Θεσσαλονίκης");
INSERT INTO municipalities (municipality) VALUES ("Δίου-Ολύμπου Νομού Πιερίας");
INSERT INTO municipalities (municipality) VALUES ("Έδεσσας Νομού Πέλλας");
INSERT INTO municipalities (municipality) VALUES ("Εμμανουήλ Παππά Νομού Σερρών");
INSERT INTO municipalities (municipality) VALUES ("Ηρακλείας Νομού Σερρών");
INSERT INTO municipalities (municipality) VALUES ("Ηρωϊκής Πόλης Νάουσας Νομού Ημαθίας");
INSERT INTO municipalities (municipality) VALUES ("Θερμαϊκού Νομού Θεσσαλονίκης");
INSERT INTO municipalities (municipality) VALUES ("Θέρμης Νομού Θεσσαλονίκης");
INSERT INTO municipalities (municipality) VALUES ("Θεσσαλονίκης Νομού Θεσσαλονίκης");
INSERT INTO municipalities (municipality) VALUES ("Καλαμαριάς Νομού Θεσσαλονίκης");
INSERT INTO municipalities (municipality) VALUES ("Κασσάνδρας Νομού Χαλκιδικής");
INSERT INTO municipalities (municipality) VALUES ("Κατερίνης Νομού Πιερίας");
INSERT INTO municipalities (municipality) VALUES ("Κιλκίς Νομού Κιλκίς");
INSERT INTO municipalities (municipality) VALUES ("Κορδελιού-Ευόσμου Νομού Θεσσαλονίκης");
INSERT INTO municipalities (municipality) VALUES ("Λαγκαδά Νομού Θεσσαλονίκης");
INSERT INTO municipalities (municipality) VALUES ("Νεάπολης-Συκεών Νομού Θεσσαλονίκης");
INSERT INTO municipalities (municipality) VALUES ("Νέας Ζίχνης Νομού Σερρών");
INSERT INTO municipalities (municipality) VALUES ("Νέας Προποντίδας Νομού Χαλκιδικής");
INSERT INTO municipalities (municipality) VALUES ("Παιονίας Νομού Κιλκίς");
INSERT INTO municipalities (municipality) VALUES ("Παύλου Μελά Νομού Θεσσαλονίκης");
INSERT INTO municipalities (municipality) VALUES ("Πέλλας Νομού Πέλλας");
INSERT INTO municipalities (municipality) VALUES ("Πολυγύρου Νομού Χαλκιδικής");
INSERT INTO municipalities (municipality) VALUES ("Πύδνας-Κολινδρού Νομού Πιερίας");
INSERT INTO municipalities (municipality) VALUES ("Πυλαίας-Χορτιάτη Νομού Θεσσαλονίκης");
INSERT INTO municipalities (municipality) VALUES ("Σερρών Νομού Σερρών");
INSERT INTO municipalities (municipality) VALUES ("Σιθωνίας Νομού Χαλκιδικής");
INSERT INTO municipalities (municipality) VALUES ("Σιντικής Νομού Σερρών");
INSERT INTO municipalities (municipality) VALUES ("Σκύδρας Νομού Πέλλας");
INSERT INTO municipalities (municipality) VALUES ("Χαλκηδόνος Νομού Θεσσαλονίκης");
INSERT INTO municipalities (municipality) VALUES ("Ωραιοκάστρου Νομού Θεσσαλονίκης");
INSERT INTO municipalities (municipality) VALUES ("Αμυνταίου Νομού Φλώρινας");
INSERT INTO municipalities (municipality) VALUES ("Άργους Ορεστικού Νομού Καστοριάς");
INSERT INTO municipalities (municipality) VALUES ("Βελβεντού Νομού Κοζάνης");
INSERT INTO municipalities (municipality) VALUES ("Βοΐου Νομού Κοζάνης");
INSERT INTO municipalities (municipality) VALUES ("Γρεβενών Νομού Γρεβενών");
INSERT INTO municipalities (municipality) VALUES ("Δεσκάτης Νομού Γρεβενών");
INSERT INTO municipalities (municipality) VALUES ("Εορδαίας Νομού Κοζάνης");
INSERT INTO municipalities (municipality) VALUES ("Καστοριάς Νομού Καστοριάς");
INSERT INTO municipalities (municipality) VALUES ("Κοζάνης Νομού Κοζάνης");
INSERT INTO municipalities (municipality) VALUES ("Νεστορίου Νομού Καστοριάς");
INSERT INTO municipalities (municipality) VALUES ("Πρεσπών Νομού Φλώρινας");
INSERT INTO municipalities (municipality) VALUES ("Σερβίων Νομού Κοζάνης");
INSERT INTO municipalities (municipality) VALUES ("Φλώρινας Νομού Φλώρινας");
INSERT INTO municipalities (municipality) VALUES ("Αρταίων Νομού Άρτας");
INSERT INTO municipalities (municipality) VALUES ("Βορείων Τζουμέρκων Νομού Ιωαννίνων");
INSERT INTO municipalities (municipality) VALUES ("Γεωργίου Καραϊσκάκη Νομού Άρτας");
INSERT INTO municipalities (municipality) VALUES ("Δωδώνης Νομού Ιωαννίνων");
INSERT INTO municipalities (municipality) VALUES ("Ζαγορίου Νομού Ιωαννίνων");
INSERT INTO municipalities (municipality) VALUES ("Ζηρού Νομού Πρεβέζης");
INSERT INTO municipalities (municipality) VALUES ("Ζίτσας Νομού Ιωαννίνων");
INSERT INTO municipalities (municipality) VALUES ("Ηγουμενίτσας Νομού Θεσπρωτίας");
INSERT INTO municipalities (municipality) VALUES ("Ιωαννιτών Νομού Ιωαννίνων");
INSERT INTO municipalities (municipality) VALUES ("Κεντρικών Τζουμέρκων Νομού Άρτας");
INSERT INTO municipalities (municipality) VALUES ("Κόνιτσας Νομού Ιωαννίνων");
INSERT INTO municipalities (municipality) VALUES ("Μετσόβου Νομού Ιωαννίνων");
INSERT INTO municipalities (municipality) VALUES ("Νικολάου Σκουφά Νομού Άρτας");
INSERT INTO municipalities (municipality) VALUES ("Πάργας Νομού Πρεβέζης");
INSERT INTO municipalities (municipality) VALUES ("Πρέβεζας Νομού Πρεβέζης");
INSERT INTO municipalities (municipality) VALUES ("Πωγωνίου Νομού Ιωαννίνων");
INSERT INTO municipalities (municipality) VALUES ("Σουλίου Νομού Θεσπρωτίας");
INSERT INTO municipalities (municipality) VALUES ("Φιλιατών Νομού Θεσπρωτίας");
INSERT INTO municipalities (municipality) VALUES ("Αγιάς Νομού Λαρίσης");
INSERT INTO municipalities (municipality) VALUES ("Αλμυρού Νομού Μαγνησίας");
INSERT INTO municipalities (municipality) VALUES ("Αλοννήσου Νομού Μαγνησίας");
INSERT INTO municipalities (municipality) VALUES ("Αργιθέας Νομού Καρδίτσας");
INSERT INTO municipalities (municipality) VALUES ("Βόλου Νομού Μαγνησίας");
INSERT INTO municipalities (municipality) VALUES ("Ελασσόνας Νομού Λαρίσης");
INSERT INTO municipalities (municipality) VALUES ("Ζαγοράς-Μουρεσίου Νομού Μαγνησίας");
INSERT INTO municipalities (municipality) VALUES ("Καρδίτσας Νομού Καρδίτσας");
INSERT INTO municipalities (municipality) VALUES ("Κιλελέρ Νομού Λαρίσης");
INSERT INTO municipalities (municipality) VALUES ("Λαρισαίων Νομού Λαρίσης");
INSERT INTO municipalities (municipality) VALUES ("Λίμνης Πλαστήρα Νομού Καρδίτσας");
INSERT INTO municipalities (municipality) VALUES ("Μετεώρων Νομού Τρικάλων");
INSERT INTO municipalities (municipality) VALUES ("Μουζακίου Νομού Καρδίτσας");
INSERT INTO municipalities (municipality) VALUES ("Νότιου Πηλίου Νομού Μαγνησίας");
INSERT INTO municipalities (municipality) VALUES ("Παλαμά Νομού Καρδίτσας");
INSERT INTO municipalities (municipality) VALUES ("Πύλης Νομού Τρικάλων");
INSERT INTO municipalities (municipality) VALUES ("Ρήγα Φεραίου Νομού Μαγνησίας");
INSERT INTO municipalities (municipality) VALUES ("Σκιάθου Νομού Μαγνησίας");
INSERT INTO municipalities (municipality) VALUES ("Σκοπέλου Νομού Μαγνησίας");
INSERT INTO municipalities (municipality) VALUES ("Σοφάδων Νομού Καρδίτσας");
INSERT INTO municipalities (municipality) VALUES ("Τεμπών Νομού Λαρίσης");
INSERT INTO municipalities (municipality) VALUES ("Τρικκαίων Νομού Τρικάλων");
INSERT INTO municipalities (municipality) VALUES ("Τυρνάβου Νομού Λαρίσης");
INSERT INTO municipalities (municipality) VALUES ("Φαρκαδόνας Νομού Τρικάλων");
INSERT INTO municipalities (municipality) VALUES ("Φαρσάλων Νομού Λαρίσης");
INSERT INTO municipalities (municipality) VALUES ("Αργοστολίου Νομού Κεφαλληνίας και Ιθάκης");
INSERT INTO municipalities (municipality) VALUES ("Βόρειας Κέρκυρας Νομού Κέρκυρας");
INSERT INTO municipalities (municipality) VALUES ("Ζακύνθου");
INSERT INTO municipalities (municipality) VALUES ("Ιθάκης");
INSERT INTO municipalities (municipality) VALUES ("Κεντρικής Κέρκυρας και Διαποντίων Νήσων Νομού Κέρκυρας");
INSERT INTO municipalities (municipality) VALUES ("Λευκάδος");
INSERT INTO municipalities (municipality) VALUES ("Ληξουρίου Νομού Κεφαλληνίας και Ιθάκης");
INSERT INTO municipalities (municipality) VALUES ("Μεγανησίου Νομού Λευκάδος");
INSERT INTO municipalities (municipality) VALUES ("Νότιας Κέρκυρας Νομού Κέρκυρας");
INSERT INTO municipalities (municipality) VALUES ("Παξών Νομού Κέρκυρας");
INSERT INTO municipalities (municipality) VALUES ("Σάμης Νομού Κεφαλληνίας και Ιθάκης");
INSERT INTO municipalities (municipality) VALUES ("Αγρινίου Νομού Αιτωλοακαρνανίας");
INSERT INTO municipalities (municipality) VALUES ("Αιγιαλείας Νομού Αχαΐας");
INSERT INTO municipalities (municipality) VALUES ("Ακτίου-Βόνιτσας Νομού Αιτωλοακαρνανίας");
INSERT INTO municipalities (municipality) VALUES ("Αμφιλοχίας Νομού Αιτωλοακαρνανίας");
INSERT INTO municipalities (municipality) VALUES ("Ανδραβίδας-Κυλλήνης Νομού Ηλείας");
INSERT INTO municipalities (municipality) VALUES ("Ανδρίτσαινας-Κρεστένων Νομού Ηλείας");
INSERT INTO municipalities (municipality) VALUES ("Αρχαίας Ολυμπίας Νομού Ηλείας");
INSERT INTO municipalities (municipality) VALUES ("Δυτικής Αχαΐας Νομού Αχαΐας");
INSERT INTO municipalities (municipality) VALUES ("Ερυμάνθου Νομού Αχαΐας");
INSERT INTO municipalities (municipality) VALUES ("Ζαχάρως Νομού Ηλείας");
INSERT INTO municipalities (municipality) VALUES ("Ήλιδας Νομού Ηλείας");
INSERT INTO municipalities (municipality) VALUES ("Θέρμου Νομού Αιτωλοακαρνανίας");
INSERT INTO municipalities (municipality) VALUES ("Ιεράς Πόλης Μεσολογγίου Νομού Αιτωλοακαρνανίας");
INSERT INTO municipalities (municipality) VALUES ("Καλαβρύτων Νομού Αχαΐας");
INSERT INTO municipalities (municipality) VALUES ("Ναυπακτίας Νομού Αιτωλοακαρνανίας");
INSERT INTO municipalities (municipality) VALUES ("Ξηρομέρου Νομού Αιτωλοακαρνανίας");
INSERT INTO municipalities (municipality) VALUES ("Πατρέων Νομού Αχαΐας");
INSERT INTO municipalities (municipality) VALUES ("Πηνειού Νομού Ηλείας");
INSERT INTO municipalities (municipality) VALUES ("Πύργου Νομού Ηλείας");
INSERT INTO municipalities (municipality) VALUES ("Αγράφων Νομού Ευρυτανίας");
INSERT INTO municipalities (municipality) VALUES ("Αλιάρτου-Θεσπιέων Νομού Βοιωτίας");
INSERT INTO municipalities (municipality) VALUES ("Αμφίκλειας-Ελάτειας Νομού Φθιώτιδας");
INSERT INTO municipalities (municipality) VALUES ("Δελφών Νομού Φωκίδας");
INSERT INTO municipalities (municipality) VALUES ("Διρφύων-Μεσσαπίων Νομού Ευβοίας");
INSERT INTO municipalities (municipality) VALUES ("Διστόμου-Αράχοβας-Αντίκυρας Νομού Βοιωτίας");
INSERT INTO municipalities (municipality) VALUES ("Δομοκού Νομού Φθιώτιδας");
INSERT INTO municipalities (municipality) VALUES ("Δωρίδος Νομού Φωκίδας");
INSERT INTO municipalities (municipality) VALUES ("Ερέτριας Νομού Ευβοίας");
INSERT INTO municipalities (municipality) VALUES ("Θηβαίων Νομού Βοιωτίας");
INSERT INTO municipalities (municipality) VALUES ("Ιστιαίας-Αιδηψού Νομού Ευβοίας");
INSERT INTO municipalities (municipality) VALUES ("Καμένων Βούρλων Νομού Φθιώτιδας");
INSERT INTO municipalities (municipality) VALUES ("Καρπενησίου Νομού Ευρυτανίας");
INSERT INTO municipalities (municipality) VALUES ("Καρύστου Νομού Ευβοίας");
INSERT INTO municipalities (municipality) VALUES ("Κύμης-Αλιβερίου Νομού Ευβοίας");
INSERT INTO municipalities (municipality) VALUES ("Λαμιέων Νομού Φθιώτιδας");
INSERT INTO municipalities (municipality) VALUES ("Λεβαδέων Νομού Βοιωτίας");
INSERT INTO municipalities (municipality) VALUES ("Λοκρών Νομού Φθιώτιδας");
INSERT INTO municipalities (municipality) VALUES ("Μακρακώμης Νομού Φθιώτιδας");
INSERT INTO municipalities (municipality) VALUES ("Μαντουδίου-Λίμνης-Αγίας Άννας Νομού Ευβοίας");
INSERT INTO municipalities (municipality) VALUES ("Ορχομενού Νομού Βοιωτίας");
INSERT INTO municipalities (municipality) VALUES ("Σκύρου Νομού Ευβοίας");
INSERT INTO municipalities (municipality) VALUES ("Στυλίδας Νομού Φθιώτιδας");
INSERT INTO municipalities (municipality) VALUES ("Τανάγρας Νομού Βοιωτίας");
INSERT INTO municipalities (municipality) VALUES ("Χαλκιδέων Νομού Ευβοίας");
INSERT INTO municipalities (municipality) VALUES ("Αγίας Βαρβάρας Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Αγίας Παρασκευής Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Αγίου Δημητρίου Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Αγίων Αναργύρων-Καματερού Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Αγκιστρίου Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Αθηναίων Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Αιγάλεω Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Αίγινας Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Αλίμου Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Αμαρουσίου Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Ασπροπύργου Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Αχαρνών Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Βάρης-Βούλας-Βουλιαγμένης Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Βριλησσίων Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Βύρωνος Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Γαλατσίου Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Γλυφάδας Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Δάφνης-Υμηττού Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Διονύσου Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Ελευσίνας Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Ελληνικού-Αργυρούπολης Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Ζωγράφου Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Ηλιουπόλεως Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Ηρακλείου Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Ιλίου Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Καισαριανής Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Καλλιθέας Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Κερατσινίου-Δραπετσώνας Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Κηφισιάς Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Κορυδαλλού Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Κρωπίας Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Κυθήρων Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Λαυρεωτικής Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Λυκόβρυσης-Πεύκης Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Μάνδρας-Ειδυλλίας Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Μαραθώνος Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Μαρκόπουλου Μεσογαίας Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Μεγαρέων Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Μεταμορφώσεως Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Μοσχάτου-Ταύρου Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Νέας Ιωνίας Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Νέας Σμύρνης Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Νέας Φιλαδέλφειας-Νέας Χαλκηδόνας Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Νίκαιας-Αγίου Ιωάννη Ρέντη Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Παιανίας Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Παλαιού Φαλήρου Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Παλλήνης Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Παπάγου-Χολαργού Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Πειραιώς Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Πεντέλης Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Περάματος Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Περιστερίου Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Πετρουπόλεως Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Πόρου Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Ραφήνας-Πικερμίου Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Σαλαμίνας Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Σαρωνικού Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Σπάτων-Αρτέμιδος Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Σπετσών Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Τροιζηνίας - Μεθάνων Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Ύδρας Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Φιλοθέης-Ψυχικού Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Φυλής Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Χαϊδαρίου Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Χαλανδρίου Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Ωρωπού Νομού Αττικής");
INSERT INTO municipalities (municipality) VALUES ("Ανατολικής Μάνης Νομού Λακωνίας");
INSERT INTO municipalities (municipality) VALUES ("Άργους-Μυκηνών Νομού Αργολίδας");
INSERT INTO municipalities (municipality) VALUES ("Βέλου-Βόχας Νομού Κορινθίας");
INSERT INTO municipalities (municipality) VALUES ("Βόρειας Κυνουρίας Νομού Αρκαδίας");
INSERT INTO municipalities (municipality) VALUES ("Γορτυνίας Νομού Αρκαδίας");
INSERT INTO municipalities (municipality) VALUES ("Δυτικής Μάνης Νομού Μεσσηνίας");
INSERT INTO municipalities (municipality) VALUES ("Ελαφονήσου Νομού Λακωνίας");
INSERT INTO municipalities (municipality) VALUES ("Επιδαύρου Νομού Αργολίδας");
INSERT INTO municipalities (municipality) VALUES ("Ερμιονίδας Νομού Αργολίδας");
INSERT INTO municipalities (municipality) VALUES ("Ευρώτα Νομού Λακωνίας");
INSERT INTO municipalities (municipality) VALUES ("Καλαμάτας Νομού Μεσσηνίας");
INSERT INTO municipalities (municipality) VALUES ("Κορινθίων Νομού Κορινθίας");
INSERT INTO municipalities (municipality) VALUES ("Λουτρακίου - Περαχώρας - Αγίων Θεοδώρων Νομού Κορινθίας");
INSERT INTO municipalities (municipality) VALUES ("Μεγαλόπολης Νομού Αρκαδίας");
INSERT INTO municipalities (municipality) VALUES ("Μεσσήνης Νομού Μεσσηνίας");
INSERT INTO municipalities (municipality) VALUES ("Μονεμβασίας Νομού Λακωνίας");
INSERT INTO municipalities (municipality) VALUES ("Ναυπλιέων Νομού Αργολίδας");
INSERT INTO municipalities (municipality) VALUES ("Νεμέας Νομού Κορινθίας");
INSERT INTO municipalities (municipality) VALUES ("Νότιας Κυνουρίας Νομού Αρκαδίας");
INSERT INTO municipalities (municipality) VALUES ("Ξυλοκάστρου-Ευρωστίνης Νομού Κορινθίας");
INSERT INTO municipalities (municipality) VALUES ("Οιχαλίας Νομού Μεσσηνίας");
INSERT INTO municipalities (municipality) VALUES ("Πύλου-Νέστορος Νομού Μεσσηνίας");
INSERT INTO municipalities (municipality) VALUES ("Σικυωνίων Νομού Κορινθίας");
INSERT INTO municipalities (municipality) VALUES ("Σπάρτης Νομού Λακωνίας");
INSERT INTO municipalities (municipality) VALUES ("Τρίπολης Νομού Αρκαδίας");
INSERT INTO municipalities (municipality) VALUES ("Τριφυλλίας Νομού Μεσσηνίας");
INSERT INTO municipalities (municipality) VALUES ("Αγίου Ευστρατίου Νομού Λέσβου");
INSERT INTO municipalities (municipality) VALUES ("Ανατολικής Σάμου Νομού Σάμου");
INSERT INTO municipalities (municipality) VALUES ("Δυτικής Λέσβου Νομού Λέσβου");
INSERT INTO municipalities (municipality) VALUES ("Δυτικής Σάμου Νομού Σάμου");
INSERT INTO municipalities (municipality) VALUES ("Ηρωϊκής Νήσου Ψαρών Νομού Χίου");
INSERT INTO municipalities (municipality) VALUES ("Ικαρίας Νομού Σάμου");
INSERT INTO municipalities (municipality) VALUES ("Λήμνου Νομού Λέσβου");
INSERT INTO municipalities (municipality) VALUES ("Μυτιλήνης Νομού Λέσβου");
INSERT INTO municipalities (municipality) VALUES ("Οινουσσών Νομού Χίου");
INSERT INTO municipalities (municipality) VALUES ("Φούρνων Κορσεών Νομού Σάμου");
INSERT INTO municipalities (municipality) VALUES ("Χίου Νομού Χίου");
INSERT INTO municipalities (municipality) VALUES ("Αγαθονησίου Νομού Δωδεκανήσου");
INSERT INTO municipalities (municipality) VALUES ("Αμοργού Νομού Κυκλάδων");
INSERT INTO municipalities (municipality) VALUES ("Ανάφης Νομού Κυκλάδων");
INSERT INTO municipalities (municipality) VALUES ("Άνδρου Νομού Κυκλάδων");
INSERT INTO municipalities (municipality) VALUES ("Αντιπάρου Νομού Κυκλάδων");
INSERT INTO municipalities (municipality) VALUES ("Αστυπάλαιας Νομού Δωδεκανήσου");
INSERT INTO municipalities (municipality) VALUES ("Ηρωϊκής Νήσου Κάσου Νομού Δωδεκανήσου");
INSERT INTO municipalities (municipality) VALUES ("Θήρας Νομού Κυκλάδων");
INSERT INTO municipalities (municipality) VALUES ("Ιητών Νομού Κυκλάδων");
INSERT INTO municipalities (municipality) VALUES ("Καλυμνίων Νομού Δωδεκανήσου");
INSERT INTO municipalities (municipality) VALUES ("Καρπάθου Νομού Δωδεκανήσου");
INSERT INTO municipalities (municipality) VALUES ("Κέας Νομού Κυκλάδων");
INSERT INTO municipalities (municipality) VALUES ("Κιμώλου Νομού Κυκλάδων");
INSERT INTO municipalities (municipality) VALUES ("Κύθνου Νομού Κυκλάδων");
INSERT INTO municipalities (municipality) VALUES ("Κω Νομού Δωδεκανήσου");
INSERT INTO municipalities (municipality) VALUES ("Λειψών Νομού Δωδεκανήσου");
INSERT INTO municipalities (municipality) VALUES ("Λέρου Νομού Δωδεκανήσου");
INSERT INTO municipalities (municipality) VALUES ("Μεγίστης Νομού Δωδεκανήσου");
INSERT INTO municipalities (municipality) VALUES ("Μήλου Νομού Κυκλάδων");
INSERT INTO municipalities (municipality) VALUES ("Μυκόνου Νομού Κυκλάδων");
INSERT INTO municipalities (municipality) VALUES ("Νάξου και Μικρών Κυκλάδων");
INSERT INTO municipalities (municipality) VALUES ("Νισύρου Νομού Δωδεκανήσου");
INSERT INTO municipalities (municipality) VALUES ("Πάρου Νομού Κυκλάδων");
INSERT INTO municipalities (municipality) VALUES ("Πάτμου Νομού Δωδεκανήσου");
INSERT INTO municipalities (municipality) VALUES ("Ρόδου Νομού Δωδεκανήσου");
INSERT INTO municipalities (municipality) VALUES ("Σερίφου Νομού Κυκλάδων");
INSERT INTO municipalities (municipality) VALUES ("Σικίνου Νομού Κυκλάδων");
INSERT INTO municipalities (municipality) VALUES ("Σίφνου Νομού Κυκλάδων");
INSERT INTO municipalities (municipality) VALUES ("Σύμης Νομού Δωδεκανήσου");
INSERT INTO municipalities (municipality) VALUES ("Σύρου-Ερμούπολης Νομού Κυκλάδων");
INSERT INTO municipalities (municipality) VALUES ("Τήλου Νομού Δωδεκανήσου");
INSERT INTO municipalities (municipality) VALUES ("Τήνου Νομού Κυκλάδων");
INSERT INTO municipalities (municipality) VALUES ("Φολεγάνδρου Νομού Κυκλάδων");
INSERT INTO municipalities (municipality) VALUES ("Χάλκης Νομού Δωδεκανήσου");
INSERT INTO municipalities (municipality) VALUES ("Αγίου Βασιλείου Νομού Ρεθύμνης");
INSERT INTO municipalities (municipality) VALUES ("Αγίου Νικολάου Νομού Λασιθίου");
INSERT INTO municipalities (municipality) VALUES ("Αμαρίου Νομού Ρεθύμνης");
INSERT INTO municipalities (municipality) VALUES ("Ανωγείων Νομού Ρεθύμνης");
INSERT INTO municipalities (municipality) VALUES ("Αποκορώνου Νομού Χανίων");
INSERT INTO municipalities (municipality) VALUES ("Αρχανών-Αστερουσίων Νομού Ηρακλείου");
INSERT INTO municipalities (municipality) VALUES ("Βιάννου Νομού Ηρακλείου");
INSERT INTO municipalities (municipality) VALUES ("Γαύδου Νομού Χανίων");
INSERT INTO municipalities (municipality) VALUES ("Γόρτυνας Νομού Ηρακλείου");
INSERT INTO municipalities (municipality) VALUES ("Ηρακλείου Νομού Ηρακλείου");
INSERT INTO municipalities (municipality) VALUES ("Ιεράπετρας Νομού Λασιθίου");
INSERT INTO municipalities (municipality) VALUES ("Καντάνου-Σελίνου Νομού Χανίων");
INSERT INTO municipalities (municipality) VALUES ("Κισσάμου Νομού Χανίων");
INSERT INTO municipalities (municipality) VALUES ("Μαλεβιζίου Νομού Ηρακλείου");
INSERT INTO municipalities (municipality) VALUES ("Μινώα Πεδιάδος Νομού Ηρακλείου");
INSERT INTO municipalities (municipality) VALUES ("Μυλοποτάμου Νομού Ρεθύμνης");
INSERT INTO municipalities (municipality) VALUES ("Οροπεδίου Λασιθίου Νομού Λασιθίου");
INSERT INTO municipalities (municipality) VALUES ("Πλατανιά Νομού Χανίων");
INSERT INTO municipalities (municipality) VALUES ("Ρεθύμνης Νομού Ρεθύμνης");
INSERT INTO municipalities (municipality) VALUES ("Σητείας Νομού Λασιθίου");
INSERT INTO municipalities (municipality) VALUES ("Σφακίων Νομού Χανίων");
INSERT INTO municipalities (municipality) VALUES ("Φαιστού Νομού Ηρακλείου");
INSERT INTO municipalities (municipality) VALUES ("Χανίων Νομού Χανίων");
INSERT INTO municipalities (municipality) VALUES ("Χερσονήσου Νομού Ηρακλείου");
